config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

    resources :swimming_pools do
    resources :bookings, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :swimming_pool

  validates :date, :participant, presence: true
end

app/models/swimming_pool.rb
class SwimmingPool < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings

  validates :name, :address, :capacity, :price, presence: true
  validates :price, :length, :width, :capacity, numericality: { only_integer: true }
  validates :availability, inclusion: { in: [true, false] }
  validates :name, length: { maximum: 100 }
  validates :description, length: { maximum: 1200 }
  validates :price, :capacity, :length, :width, length: { maximum: 3 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :swimming_pools, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @swimming_pool = SwimmingPool.find(params[:swimming_pool_id])
    @swimming_pool = @booking.swimming_pool

    if @booking.save
      redirect_to root_path, notice: "votre réservation a bien été enregistrée !" # A modifier lors de la creation du dashboard#profil
    else
      render "swimming_pools/show"
    end
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date, :participant)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/swimming_pools_controller.rb
class SwimmingPoolsController < ApplicationController
  before_action :find_swimming_pool, only: [:show, :edit, :update, :destroy]

  def index
    @swimming_pools = SwimmingPool.where.not(latitude: nil, longitude: nil)

    @markers = @swimming_pools.map do |swimming_pool|
      {
        lat: swimming_pool.latitude,
        lng: swimming_pool.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { swimming_pool: swimming_pool })
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @swimming_pool = SwimmingPool.new
  end

  def create
    @swimming_pool = SwimmingPool.new(swimming_pool_params)
    if @swimming_pool.save
      redirect_to @swimming_pool, notice: "Votre piscine a bien été enregistrée !"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @swimming_pool.update(swimming_pool_params)
      redirect_to @swimming_pool, notice: "Votre piscine a bien été modifiée !"
    else
      render :edit
    end
  end

  def destroy
    @swimming_pool.destroy
    redirect_to swimming_pools_path, notice: "Votre piscine a bien été supprimée !"
  end

  private

  def swimming_pool_params
    params.require(:swimming_pool).permit(:name, :description, :address, :length, :width, :heated, :type, :capacity, :availability, :price)
  end

  def find_swimming_pool
    @swimming_pool = SwimmingPool.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-title">
    <h1>Le bonheur se partage</h1>
    <p>La solution idéale pour votre location de piscine.</p>
    <%= link_to "Voir les piscines", swimming_pools_path, {class: "btn btn-primary"} %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-water"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/swimming_pools/_infowindow.html.erb
<h1> <%= swimming_pool.name %> </h1>

app/views/swimming_pools/edit.html.erb
<h1>Modifiez votre piscine</h1>

<%= simple_form_for @swimming_pool do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :description %>

  <%= f.input :address %>

  <%= f.input :length %>

  <%= f.input :width %>

  <%= f.input :heated, as: :radio_buttons %>

  <%= f.input :capacity %>

  <%= f.input :price %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/swimming_pools/index.html.erb
<div class="searchpage-container">
  <div class="cards-product">
    <% @swimming_pools.each do |swimming_pool| %>
      <%= link_to swimming_pool_path(swimming_pool), :action => 'go' do %>
        <div class="card-product">
          <%= image_tag swimming_pool.picture %>
          <div class="card-product-infos">
            <div class="card-product-pricing">
              <h2 class="card-product-price"><%= swimming_pool.price %>€</h2>
              <span>par personne</span>
              <span>(la journée)</span>
            </div>
            <div class="card-product-title">
              <h2><%= swimming_pool.name %></h2>
              <span>proposé par Bernard de Lavillardière</span>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/swimming_pools/new.html.erb
<h1>Créer votre piscine</h1>

<%= simple_form_for @swimming_pool do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :description %>

  <%= f.input :address %>

  <%= f.input :length %>

  <%= f.input :width %>

  <%= f.input :heated, as: :radio_buttons %>

  <%= f.input :capacity %>

  <%= f.input :price %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/swimming_pools/show.html.erb
<div class="page-booking">
  <%= image_tag @swimming_pool.picture %>
  <div class="container d-flex mt-5">
    <div class="row">
      <div class="col-8">
        <div class="card-product-booking">
          <div class="card-product-booking-infos">
            <div class="card-product-booking-pricing">
              <h2 class="card-product-booking-price"><%= @swimming_pool.price %>€</h2>
              <span>par personne</span>
              <span>(la journée)</span>
            </div>
            <div class="card-product-booking-title">
              <h2><%= @swimming_pool.name %></h2>
              <span>proposé par Bernard de Lavillardière</span>
            </div>
          </div>
        </div>
        <div class="booking-swimming-pool-info">
          <h3>Description</h3>
          <p><%= @swimming_pool.description %></p>
        </div>
        <div class="booking-swimming-pool-info">
          <h3>Taille de la piscine</h3>
          <p>Longueur: <%= @swimming_pool.length %> m / Largeur: <%= @swimming_pool.width %> m</p>
        </div>
        <div class="booking-swimming-pool-info">
          <h3>Piscine chauffée</h3>
          <% if @swimming_pool.heated %>
            <%= "oui" %>
          <% else %>
            <%= "non" %>
          <% end %>
        </div>
        <div class="booking-swimming-pool-info">
          <h3>Capacité d'accueil</h3>
          <p><%= @swimming_pool.capacity %> personnes</p>
        </div>
      </div>
      <div class="col-4">
        <div class="form-booking">
          <h3 class="form-booking-title">Réserver cette piscine</h3>
          <%= simple_form_for [@swimming_pool, @booking] do |f| %>
            <%= f.error_notification %>
            <%= f.input :date %>
            <%= f.input :participant %>

            <%= f.button :submit, class: "btn-primary" %>
            <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>